### ISSUE TITLE
Exception if state_vedgeList is empty for MT with no edge devices

### ISSUE THREAD

**Issue by jacontre-c** [CiscoDevNet/sure#10]
mt-vmanage1:~/sdwan_sure$ cat sure_report_22_01_2022_08_15_31.txt
Cisco SDWAN AURA v1.0.8 Report

Cisco SDWAN AURA command line tool performed a total of 32 checks at different levels of the SDWAN overlay.

Reach out to sure-tool@cisco.com  if you have any questions or feedback

Summary of the Results:
-----------------------------------------------------------------------------------------------------------------

mt-vmanage1:~/sdwan_sure$ cat sure_logs_22_01_2022_08_15_31.log
INFO:Executing the script in Normal execution mode
INFO:Generating a JSessionID
INFO:Generating CSRF Token
INFO:****Collecting Preliminary Data

ERROR:'state_vedgeList'
Traceback (most recent call last):
  File "./sure.py", line 2499, in <module>
    controllers_info = controllersInfo(controllers)
  File "./sure.py", line 327, in controllersInfo
    controllers_info[(device['host-name'])] = [(device['deviceType']),(device['deviceIP']),(device['version']) ,(device['reachability']),(device['globalState']),(device['timeRemainingForExpiration']), (device['state_vedgeList']) ]
KeyError: 'state_vedgeList'
mt-vmanage1:~/sdwan_sure$

**Comment by rukapse** [comment]
Maybe a better error message like ' no edge devices found' ?

**Comment by rukapse** [comment]
`if 'state_vedgeList' in device.keys():
				controllers_info[(device['host-name'])] = [(device['deviceType']),(device['deviceIP']),(device['version']) ,(device['reachability']),(device['globalState']),(device['timeRemainingForExpiration']), (device['state_vedgeList']) ] 
			else:
				controllers_info[(device['host-name'])] = [(device['deviceType']),(device['deviceIP']),(device['version']) ,(device['reachability']),(device['globalState']),(device['timeRemainingForExpiration']), 'no-vedges' ] `

**Comment by rukapse** [comment]
Placed a condition to store data controllers_info = {} only if state_vedgeList is present in the device information:
`if 'state_vedgeList' in device.keys():` 

Else it will store, 'no-edges' in the controllers_info.
