### ISSUE TITLE
Error in Check 26, system-ip'

### ISSUE THREAD

**Issue by jacontre-c** [CiscoDevNet/sure#13]
INFO:#26:Check:Cluster:Cluster health
ERROR:'system-ip'
Traceback (most recent call last):
  File "sure.py", line 4329, in <module>
    services_down, check_result, check_analysis, check_action = criticalCheckthirteen(cluster_health_data)
  File "sure.py", line 932, in criticalCheckthirteen
    (device['configJson'].pop('system-ip'))

**Comment by rukapse** [comment]
It look like the API ‘clusterManagement/list' has the system-ip key pair missing.
