### ISSUE TITLE
Error in check 22 UnboundLocalError: local variable 'check_result' referenced before assignmen

### ISSUE THREAD

**Issue by jacontre-c** [CiscoDevNet/sure#14]
INFO:#22:Check:vManage:Disk controller type
ERROR:local variable 'check_result' referenced before assignment
Traceback (most recent call last):
  File "sure.py", line 4208, in <module>
    check_result, check_analysis, check_action = infoCheckone(server_type, disk_controller)
  File "sure.py", line 1387, in infoCheckone
    return check_result, check_analysis, check_action
UnboundLocalError: local variable 'check_result' referenced before assignment

**Comment by rukapse** [comment]
Condition has skipped server type 'on-prem' or 'on-cloud'

**Comment by rukapse** [comment]
Added a else condition to return 'Unable to identify the Disk controller type'.
