### ISSUE TITLE
Error in check 11 IndexError: list index out of range

### ISSUE THREAD

**Issue by jacontre-c** [CiscoDevNet/sure#15]
INFO:#11:Check:Controllers:Validate vSmart/vBond CPU count for scale
ERROR:list index out of range
Traceback (most recent call last):
  File "sure.py", line 3880, in <module>
    total_cpu_count = int(output['data'][0]['total_cpu_count'])
IndexError: list index out of range

**Comment by rukapse** [comment]
The Endpoint is not returning any data. 

Placed a condition if the the data == [] then total_cpu_count = 0
