### ISSUE TITLE
Error in check 5 TypeError: the JSON object must be str, not 'NoneType'

### ISSUE THREAD

**Issue by jacontre-c** [CiscoDevNet/sure#17]
INFO:#05:Check:vManage:ElasticSearch Indices status
ERROR:the JSON object must be str, not 'NoneType'
Traceback (most recent call last):
  File "sure.py", line 3696, in <module>
    es_indexes_one = json.loads(getRequestpy3(version_tuple,vmanage_lo_ip, jsessionid, 'management/elasticsearch/index/info', args.vmanage_port, tokenid))
  File "/usr/lib/python3.5/json/__init__.py", line 312, in loads
    s.__class__.__name__))
TypeError: the JSON object must be str, not 'NoneType'

**Comment by rukapse** [comment]
API retrieving incorrect data.
After this scope should be able to use the API
https://cdetsng.cisco.com/summary/#/defect/CSCwa94955

Meanwhile, do curl to get ES Indices data
