### ISSUE TITLE
Need to sanitize user input & perform error handling

### ISSUE THREAD

**Issue by naveci** [CiscoDevNet/sure#24]
Hi all,

I was struggling a little with getting this script to work. I had the consistently the same error in the logs:
```
INFO:Executing the script in Verbose execution mode
INFO:Generating a JSessionID
ERROR:list index out of range
Traceback (most recent call last):
  File "sure.py", line 8354, in <module>
    jsessionid = generateSessionID(vmanage_lo_ip, args.username, password, args.vmanage_port)
  File "sure.py", line 211, in generateSessionID
    jsessionid = (login[3].split('=')[1][0:-1])
IndexError: list index out of range
```

The problem turns out to be in the password, because the user input was not sanitized. I had several special characters in the password, including a quote sign etc.
Perform error handling would've dealt with this issue in a better way. More importantly, sanitizing user input would prevent the script from breaking in the first place.

**Comment by ProsperousHeart** [comment]
Thank you for bringing this to our attention. This will be worked on under internal Jira CEADETT-135. No ETA as of yet.

**Comment by rukapse** [comment]
Jira ticket
https://jira-eng-sjc4.cisco.com/jira/browse/SDWANAURA-39
