### ISSUE TITLE
Add support for DB size check

### ISSUE THREAD

**Issue by javcon** [CiscoDevNet/sure#26]
Implement check based on output from command in CSCvx69668
Report critical error if DB is >=5GB

**Comment by rukapse** [comment]
vmanage-v203# request nms configuration-db diagnostics 
NMS configuration database
Checking cluster connectivity...
Pinging server 0 on localhost:7687,7474...
Starting Nping 0.7.60 ( https://nmap.org/nping ) at 2022-08-30 16:18 UTC
SENT (0.0020s) Starting TCP Handshake > localhost:7474 ([127.0.0.1:7474](https://127.0.0.1:7474/))
RCVD (0.0020s) Handshake with localhost:7474 ([127.0.0.1:7474](https://127.0.0.1:7474/)) completed
SENT (1.0032s) Starting TCP Handshake > localhost:7687 ([127.0.0.1:7687](https://127.0.0.1:7687/))
RCVD (1.0032s) Handshake with localhost:7687 ([127.0.0.1:7687](https://127.0.0.1:7687/)) completed
SENT (2.0043s) Starting TCP Handshake > localhost:7474 ([127.0.0.1:7474](https://127.0.0.1:7474/))
RCVD (2.0043s) Handshake with localhost:7474 ([127.0.0.1:7474](https://127.0.0.1:7474/)) completed
SENT (3.0053s) Starting TCP Handshake > localhost:7687 ([127.0.0.1:7687](https://127.0.0.1:7687/))
RCVD (3.0053s) Handshake with localhost:7687 ([127.0.0.1:7687](https://127.0.0.1:7687/)) completed
SENT (4.0064s) Starting TCP Handshake > localhost:7474 ([127.0.0.1:7474](https://127.0.0.1:7474/))
RCVD (4.0064s) Handshake with localhost:7474 ([127.0.0.1:7474](https://127.0.0.1:7474/)) completed
SENT (5.0074s) Starting TCP Handshake > localhost:7687 ([127.0.0.1:7687](https://127.0.0.1:7687/))
RCVD (5.0074s) Handshake with localhost:7687 ([127.0.0.1:7687](https://127.0.0.1:7687/)) completed
 
Max rtt: 0.022ms | Min rtt: 0.011ms | Avg rtt: 0.019ms
TCP connection attempts: 6 | Successful connections: 6 | Failed: 0 (0.00%)
Nping done: 1 IP address pinged in 5.01 seconds

Connecting to localhost...
+------------------------------------------------------------------------------------+
| type             | row                                  | attributes[row]['value'] |
+------------------------------------------------------------------------------------+
| "StoreSizes"     | "LogicalLogSize"                     | 32667521                 |
| "StoreSizes"     | "StringStoreSize"                    | 1671168                  |
| "StoreSizes"     | "ArrayStoreSize"                     | 212992                   |
| "StoreSizes"     | "RelationshipStoreSize"              | 65280                    |
| "StoreSizes"     | "PropertyStoreSize"                  | 473222                   |
| "StoreSizes"     | "NodeStoreSize"                      | 32760                    |
| "StoreSizes"     | "TotalStoreSize"                     | 476748984                |
| "PageCache"      | "Hits"                               | 453467                   |
| "PageCache"      | "FileUnmappings"                     | 437                      |
| "PageCache"      | "FileMappings"                       | 834                      |
| "PageCache"      | "Faults"                             | 3525                     |
| "PageCache"      | "EvictionExceptions"                 | 0                        |
| "PageCache"      | "Flushes"                            | 820                      |
| "PageCache"      | "BytesWritten"                       | 7657617                  |
| "PageCache"      | "UsageRatio"                         | 0.026998874089506054     |
| "PageCache"      | "Unpins"                             | 455647                   |
| "PageCache"      | "Evictions"                          | 0                        |
| "PageCache"      | "Pins"                               | 456992                   |
| "PageCache"      | "BytesRead"                          | 28828517                 |
| "PageCache"      | "HitRatio"                           | 0.9922865170506268       |
| "ID Allocations" | "NumberOfRelationshipIdsInUse"       | 1798                     |
| "ID Allocations" | "NumberOfPropertyIdsInUse"           | 11394                    |
| "ID Allocations" | "NumberOfNodeIdsInUse"               | 1948                     |
| "ID Allocations" | "NumberOfRelationshipTypeIdsInUse"   | 40                       |
| "Transactions"   | "NumberOfRolledBackTransactions"     | 572                      |
| "Transactions"   | "LastCommittedTxId"                  | 5026076                  |
| "Transactions"   | "NumberOfOpenTransactions"           | 1                        |
| "Transactions"   | "NumberOfOpenedTransactions"         | 3769                     |
| "Transactions"   | "PeakNumberOfConcurrentTransactions" | 6                        |
| "Transactions"   | "NumberOfCommittedTransactions"      | 3196                     |
+------------------------------------------------------------------------------------+

30 rows available after 121 ms, consumed after another 0 ms
Completed
Disk space used by configuration-db
833M    .
vmanage-v203#

**Comment by rukapse** [comment]
vmanage-cluster1# request nms configuration-db diagnostics
NMS configuration database
Checking cluster connectivity...
Pinging server 0 on 102.0.31.12:7687,7474...
Starting Nping 0.7.60 ( https://nmap.org/nping ) at 2022-08-30 16:20 UTC
SENT (0.0013s) Starting TCP Handshake > 102.0.31.12:7474
RCVD (0.0013s) Handshake with 102.0.31.12:7474 completed
SENT (1.0024s) Starting TCP Handshake > 102.0.31.12:7687
RCVD (1.0024s) Handshake with 102.0.31.12:7687 completed
SENT (2.0035s) Starting TCP Handshake > 102.0.31.12:7474
RCVD (2.0035s) Handshake with 102.0.31.12:7474 completed
SENT (3.0047s) Starting TCP Handshake > 102.0.31.12:7687
RCVD (3.0048s) Handshake with 102.0.31.12:7687 completed
SENT (4.0059s) Starting TCP Handshake > 102.0.31.12:7474
RCVD (4.0059s) Handshake with 102.0.31.12:7474 completed
SENT (5.0071s) Starting TCP Handshake > 102.0.31.12:7687
RCVD (5.0071s) Handshake with 102.0.31.12:7687 completed
Max rtt: 0.031ms | Min rtt: 0.010ms | Avg rtt: 0.020ms
TCP connection attempts: 6 | Successful connections: 6 | Failed: 0 (0.00%)
Nping done: 1 IP address pinged in 5.01 seconds
 
Pinging server 1 on 102.0.31.13:7687,7474...
Starting Nping 0.7.60 ( https://nmap.org/nping ) at 2022-08-30 16:21 UTC
SENT (0.0016s) Starting TCP Handshake > 102.0.31.13:7474
RCVD (0.0017s) Handshake with 102.0.31.13:7474 completed
SENT (1.0029s) Starting TCP Handshake > 102.0.31.13:7687
RCVD (1.0031s) Handshake with 102.0.31.13:7687 completed
SENT (2.0040s) Starting TCP Handshake > 102.0.31.13:7474
RCVD (2.0041s) Handshake with 102.0.31.13:7474 completed
SENT (3.0052s) Starting TCP Handshake > 102.0.31.13:7687
RCVD (3.0053s) Handshake with 102.0.31.13:7687 completed
SENT (4.0065s) Starting TCP Handshake > 102.0.31.13:7474
RCVD (4.0066s) Handshake with 102.0.31.13:7474 completed
SENT (5.0078s) Starting TCP Handshake > 102.0.31.13:7687
RCVD (5.0080s) Handshake with 102.0.31.13:7687 completed
Max rtt: 0.266ms | Min rtt: 0.108ms | Avg rtt: 0.162ms
TCP connection attempts: 6 | Successful connections: 6 | Failed: 0 (0.00%)
Nping done: 1 IP address pinged in 5.01 seconds
 
Pinging server 2 on 102.0.31.14:7687,7474...
Starting Nping 0.7.60 ( https://nmap.org/nping ) at 2022-08-30 16:21 UTC
SENT (0.0012s) Starting TCP Handshake > 102.0.31.14:7474
RCVD (0.0014s) Handshake with 102.0.31.14:7474 completed
SENT (1.0025s) Starting TCP Handshake > 102.0.31.14:7687
RCVD (1.0026s) Handshake with 102.0.31.14:7687 completed
SENT (2.0037s) Starting TCP Handshake > 102.0.31.14:7474
RCVD (2.0039s) Handshake with 102.0.31.14:7474 completed
SENT (3.0050s) Starting TCP Handshake > 102.0.31.14:7687
RCVD (3.0052s) Handshake with 102.0.31.14:7687 completed
SENT (4.0063s) Starting TCP Handshake > 102.0.31.14:7474
RCVD (4.0065s) Handshake with 102.0.31.14:7474 completed
SENT (5.0077s) Starting TCP Handshake > 102.0.31.14:7687
RCVD (5.0082s) Handshake with 102.0.31.14:7687 completed
Max rtt: 0.513ms | Min rtt: 0.118ms | Avg rtt: 0.211ms
TCP connection attempts: 6 | Successful connections: 6 | Failed: 0 (0.00%)
Nping done: 1 IP address pinged in 5.01 seconds
 
Connecting to 102.0.31.12...
+------------------------------------------------------------------------------------+
| type             | row                                  | attributes[row]['value'] |
+------------------------------------------------------------------------------------+
| "StoreSizes"     | "LogicalLogSize"                     | 78062635                 |
| "StoreSizes"     | "StringStoreSize"                    | 15777792                 |
| "StoreSizes"     | "ArrayStoreSize"                     | 1802240                  |
| "StoreSizes"     | "RelationshipStoreSize"              | 505920                   |
| "StoreSizes"     | "PropertyStoreSize"                  | 1835775                  |
| "StoreSizes"     | "NodeStoreSize"                      | 229320                   |
| "StoreSizes"     | "TotalStoreSize"                     | 542153185                |
| "PageCache"      | "Hits"                               | 3071037758               |
| "PageCache"      | "FileUnmappings"                     | 23391                    |
| "PageCache"      | "FileMappings"                       | 23822                    |
| "PageCache"      | "Faults"                             | 13425                    |
| "PageCache"      | "EvictionExceptions"                 | 0                        |
| "PageCache"      | "BytesWritten"                       | 96913980032              |
| "PageCache"      | "Flushes"                            | 11082977                 |
| "PageCache"      | "UsageRatio"                         | 0.1028254991919486       |
| "PageCache"      | "Unpins"                             | 3065841060               |
| "PageCache"      | "Evictions"                          | 0                        |
| "PageCache"      | "BytesRead"                          | 98639379                 |
| "PageCache"      | "Pins"                               | 3076541947               |
| "PageCache"      | "HitRatio"                           | 0.9999956285326425       |
| "ID Allocations" | "NumberOfRelationshipIdsInUse"       | 14663                    |
| "ID Allocations" | "NumberOfPropertyIdsInUse"           | 44221                    |
| "ID Allocations" | "NumberOfNodeIdsInUse"               | 14794                    |
| "ID Allocations" | "NumberOfRelationshipTypeIdsInUse"   | 112                      |
| "Transactions"   | "NumberOfRolledBackTransactions"     | 3870440                  |
| "Transactions"   | "LastCommittedTxId"                  | 11690923                 |
| "Transactions"   | "NumberOfOpenTransactions"           | 1                        |
| "Transactions"   | "NumberOfOpenedTransactions"         | 7432175                  |
| "Transactions"   | "PeakNumberOfConcurrentTransactions" | 5                        |
| "Transactions"   | "NumberOfCommittedTransactions"      | 3561734                  |
| "Causal Cluster" | "Role"                               | "LEADER"                 |
| "Causal Cluster" | "ReplicatedStateSize"                | 334505                   |
| "Causal Cluster" | "RaftLogSize"                        | 1100887527               |
+------------------------------------------------------------------------------------+
 
33 rows available after 355 ms, consumed after another 0 ms
Completed
Disk space used by configuration-db
2.0G

**Comment by rukapse** [comment]
Command to get the DB size: request nms configuration-db diagnostics
