### ISSUE TITLE
Tool fails with ERROR:'version'

### ISSUE THREAD

**Issue by jacontre-c** [CiscoDevNet/sure#3]
During initial data capture, the tools fails with:

ERROR:'version'
Traceback (most recent call last):
  File "sure.py", line 9362, in <module>
    controllers_info = controllersInfo(controllers)
  File "sure.py", line 327, in controllersInfo
    controllers_info[(device['host-name'])] = [(device['deviceType']),(device['deviceIP']),(device['version']) ,(device['reachability']),(device['globalState']),(device['timeRemainingForExpiration']), (device['state_vedgeList']) ]
KeyError: 'version'

Trigger is a controller on transition state, without full information, possibly on partial install state
The fix will have two parts:
1. handle properly this condition and gracefully skip over those entries
2.  add a check reporting how many entries like this have been found, with their IP addresses, so user can check on them

**Comment by jacontre-c** [comment]
Fixed in 1.0.6.

**Comment by ProsperousHeart** [comment]
Appears to have been re-introduced

**Comment by rukapse** [comment]
JIRA Ticket: https://jira-eng-sjc4.cisco.com/jira/browse/SDWANAURA-24
