### ISSUE TITLE
Monitor CPU for wildfly and statsdb

### ISSUE THREAD

**Issue by rukapse** [CiscoDevNet/sure#31]
We should monitor the memory and cpu per nms service as well like how we do for the neo4j, also wildfly, statsdb

**Comment by ProsperousHeart** [comment]
Internal discussions will be under Jira CEADETT-132

**Comment by rukapse** [comment]
Follow up with Manikandan and Arnab to get additional information on this!

**Comment by rukapse** [comment]
https://jira-eng-sjc4.cisco.com/jira/browse/SDWANAURA-44

**Comment by rukapse** [comment]
![image](https://user-images.githubusercontent.com/89453872/228759753-0ce008a4-23ca-41a9-9e02-632d370ea4fb.png)
