### ISSUE TITLE
Add warning incase DB Slicing is required.

### ISSUE THREAD

**Issue by rukapse** [CiscoDevNet/sure#32]
in neo4j we need to check the configdb size , and put a warning incase slicing of DB is required.

**Comment by rukapse** [comment]
Already added a check for checking the configdb size.
https://github.com/CiscoDevNet/sure/issues/26

**Comment by ProsperousHeart** [comment]
@rukapse - if this has already been completed, please close this issue.

**Comment by rukapse** [comment]
Follow up with Manikandan and Arnab to get additional information on this!
