### ISSUE TITLE
Return the roundtrip delay for intercluster comm.

### ISSUE THREAD

**Issue by rukapse** [CiscoDevNet/sure#33]
Intercluster communication we may need to tell the Roundtrip delay

**Comment by ProsperousHeart** [comment]
added to internal Jira CEADETT-130

**Comment by rukapse** [comment]
InterCluster communication, critical check seventeen. There are twi functions, one for python3 and one for py2.

**Comment by rukapse** [comment]
Jira Ticker 
https://jira-eng-sjc4.cisco.com/jira/browse/SDWANAURA-46
