### ISSUE TITLE
Exception error if script is executed in multi-tenant server

### ISSUE THREAD

**Issue by jacontre-c** [CiscoDevNet/sure#9]
vedge count is never initialized as json parsing fails on null returned by API call

**Comment by rukapse** [comment]
`def vedgeCount(vedges):
	vedge_count = 0  
	vedge_count_active = 0
	vedge_info = {} #Initiliazed the vedge_info
	print(vedges)
	if 'data' in vedges.keys(): 
		for vedge in vedges['data']:
			vedge_count+=1
			if 'version' in vedge.keys():
				vedge_count_active +=1
				vedge_info[(vedge['host-name'])] = [vedge['version'] , 
													vedge['validity'],
													vedge['reachability']
												   ]

	return vedge_count, vedge_count_active, vedge_info `

**Comment by rukapse** [comment]
`def vedgeCount(vedges):
	vedge_count = 0
	vedge_count_active = 0
	vedge_info = {}
	print(vedges)
	if 'data' in vedges.keys():
		for vedge in vedges['data']:
			vedge_count+=1
			if 'version' in vedge.keys():
				vedge_count_active +=1
				vedge_info[(vedge['host-name'])] = [vedge['version'] , 
													vedge['validity'],
													vedge['reachability']
												   ]

	return vedge_count, vedge_count_active, vedge_info `

**Comment by rukapse** [comment]
`def vedgeCount(vedges):`
`	vedge_count = 0
``	vedge_count_active = 0
``	vedge_info = {}
``	print(vedges)
``	if 'data' in vedges.keys():
``		for vedge in vedges['data']:
``			vedge_count+=1
``			if 'version' in vedge.keys():
``				vedge_count_active +=1
```				vedge_info[(vedge['host-name'])] = [vedge['version'] , vedge['validity'],vedge['reachability']]
`
`	return vedge_count, vedge_count_active, vedge_info `

**Comment by rukapse** [comment]
Initialize the vedge_count and vedge_count_active to zero.
Placed a if condition to only retrieve vEdge information incase the endpoint returns data.
